sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/vcs
